### ISSUE TITLE
Unable to render configuration form for Parameterized Builds for Jenkins

### ISSUE THREAD

**Issue by 3XC1T3D** [KyleLNicholls/parameterized-builds#162] opened 2018-10-30 07:47 UTC
Plugin is not working after update to 3.2.7 on 5.15.0 and 5.11.1 bitbucket

When i downgrade to 3.2.6 everything is working like a charm.

http://prntscr.com/lbnw73

When opening the Settings i get the Error

"Unable to render configuration form for Parameterized Builds for Jenkins"

When i take e look in the developer tools of the Browser i get following Error in Console

Downloading resources:
js!/s/740de78d05243a3b5e207437d70ddba5-T/390902063/bd5e9b4/1/9e4f3a1e87080a4c5eeb0f848ce2b797/_/download/contextbatch/js/com.kylenicholls.stash.parameterized-builds:parameterized-build-hook-config-form,-_super,-bitbucket.page.settings.hooks,-bitbucket.layout.repository,-atl.general/batch.js?locale=en-US!order

on the network analytics of the developer tools i can extract the setting url - and i get a valid json.

**Comment by a-hacker** [comment] 2018-10-31 00:41
Hello @3XC1T3D and @ruicapmi.

Version 3.2.7 of this plugin involved an overhaul of the javascript in the repository hook modal. During early development of this change, I experienced the same issue but thought I resolved it by changing the location of the javascript. Although that worked for my test environment, it seems the issue is still lingering. I have tested upgrading from multiple versions of the plugin on multiple different versions on Bitbucket on multiple different computers running different operating systems. I cannot replicate this issue at all.

I suspect Bitbucket might be trying to use the old version of the javascript that no longer exists. As such I've drafted a new release that might force Bitbucket to recognize that the config has changed. The release is located [here](https://github.com/KyleLNicholls/parameterized-builds/releases/tag/3.2.7-hotfix). There is a jar attached. Please manually upload that jar and see if the problem persists. This "hotfix" is purely a stab in the dark though so I'm not so confident about it.

If that fix does not work, I will need some steps to recreate the issue. Please follow the [developer documentation](https://github.com/KyleLNicholls/parameterized-builds/wiki/Developer-Guide) on getting a local Bitbucket environment stood up and use that to replicate the issue.

**Comment by ntende** [comment] 2018-10-31 10:29
Similar issue  Hot fix  resolves the issue for me  Bitbucket v5.15.0

**Comment by 3XC1T3D** [comment] 2018-10-31 13:41
Hi @a-hacker ,

thank you, for the HotFix. Unfortunately I can't test it this week. I'll try the HotFix next week on our BitBucket Installation.

Best regards

**Comment by 3XC1T3D** [comment] 2018-11-05 16:37
Hi @a-hacker ,

today we've tried the HotFix. It's working. The Error ist gone.

Thank you for the fast Support :)

**Comment by a-hacker** [comment] 2018-11-06 00:39
Version 3.2.8 has been released with this fix.

**Closed by a-hacker** 2018-11-06 00:39 UTC
Labels: bug
