### ISSUE TITLE
Problem with pattern for Ref Filter

### ISSUE THREAD

**Issue by devalru** [KyleLNicholls/parameterized-builds#91] opened 2017-08-03 09:15 UTC
Hi, 

we are using version 2.6.3 and the pattern
"develop.*" 
as Ref Filter. The Jenkins-Job should triggered only when the branchname matches the regex.

The problem ist, that the job is triggered, when the branch has i.e. this name:
origin/bugfix/PRODUKT-2073-email-benachrichtigung-bei-abgebrochenen

Our question:
Is this a bug or should we escape characters in the pattern ?

Thank you very much :)

Alex

**Comment by devalru** [comment] 2017-08-03 10:10
Some additional info. We see that two requests are fired after an (A -> B) pull-request merge. One request with BRANCH=B and one request with BRANCH=A !??

**Comment by a-hacker** [comment] 2017-08-03 12:42
May I ask what triggers you are using?

**Comment by devalru** [comment] 2017-08-03 14:06
PUSH and PR MERGED.
Ok I see the filter is not supported when PR MERGED is fired... right ?







Von meinem Samsung Ger�t gesendet.



-------- Urspr�ngliche Nachricht --------
Von: Austin Hacker <notifications@github.com> 
Datum: 03.08.2017 14:42 (GMT+01:00) 
An: KyleLNicholls/parameterized-builds <parameterized-builds@noreply.github.com> 
Cc: "Rutkowski, Alexander" <Alexander.Rutkowski@adesso.de>, Author <author@noreply.github.com>

Betreff: Re: [KyleLNicholls/parameterized-builds] Problem with pattern for Ref Filter (#91)



May I ask what triggers you are using?
—
You are receiving this because you authored the thread.
Reply to this email directly, 
view it on GitHub, or 
mute the thread.








-------------------------------------------------------     >>> business. people. technology. <<<-------------------------------------------------------adesso AG mit Sitz in DortmundVorstand: Michael Kenfenheuer (Vors.), Christoph Junge, Andreas PrenneisVorsitzender des Aufsichtsrates: Prof. Dr. Volker GruhnAmtsgericht Dortmund HRB 20663

**Comment by a-hacker** [comment] 2017-08-03 14:20
Yes. Currently, you cannot do any sort of branch filter on any of the PR actions. However, you can on the other triggers. I have an open PR for a pr-destination filter but that will only be available on Bitbucket version 5.X.

As for the double triggers in your second comment, when a PR is merged it causes a push on the destination branch. Because you have both `PUSH` and `PR MERGED` selected, you get a build for both triggers. I'd recommend deselecting `PR MERGED`. That way you can only trigger builds for some branches using the `Ref Filter` field.

**Comment by a-hacker** [comment] 2017-08-04 03:04
@devalru, I am closing this issue since there is not a bug. If you would like to request a feature, feel free to open up a new issue.

**Closed by a-hacker** 2017-08-04 03:04 UTC
