### ISSUE TITLE
"Test Jekins Settings" fails with "Failed to establish connection"

### ISSUE THREAD

**Issue by danielkoch** [KyleLNicholls/parameterized-builds#230] opened 2019-10-10 20:55 UTC
I try to establish a connection between my Jenkins and Bitbucket instance.

### Bug
After inserting all information on Bitbucket side and clicking on "Test Jekins Settings" I get the following error:
"Failed to establish connection!

In the Bitbucket log I can find the following warning:
```
2019-10-10 22:22:22,111 WARN  [http-nio-7990-exec-3] <username> @hash <ip>,<ip> "POST /rest/parameterized-builds/latest/global/servers/validate HTTP/1.1" c.k.s.p.ciserver.Jenkins Could not connect to <jenkins-instance-url>, got HTTP status 401.
```

- _Parameterized Builds for Jenkins_ plugin version: 4.0.7
- _Bitbucket_ version: 6.6.1
- _Jenkins_ Version: 2.198

**Comment by a-hacker** [comment] 2019-10-20 17:31
Fixed in 4.0.8

**Closed by a-hacker** 2019-10-20 17:31 UTC

**Comment by danielkoch** [comment] 2019-10-22 10:19
Updated to version `4.0.8`. I get the same error.

**Comment by damyan** [comment] 2019-10-22 10:47
> Updated to version `4.0.8`. I get the same error.
Same here.

**Comment by a-hacker** [comment] 2019-10-22 13:38
@danielkoch, @damyan  Do jobs trigger properly or do they also fail? Do you have a user token set up for the project?

**Comment by danielkoch** [comment] 2019-10-22 17:47
Trigger works. I use a user token based on project base.

**Comment by a-hacker** [comment] 2019-10-27 15:47
@danielkoch, I am unable to reproduce the issue on the latest build (4.0.8). I am seeing that Test Jenkins Settings will use the correct token when applicable. If you can provide a reproducible example, I'll re-open this issue.
