### ISSUE TITLE
Passing parameters in Parameterized Builds for Multibranch pipeline job is not working

### ISSUE THREAD

**Issue by kishs1991** [KyleLNicholls/parameterized-builds#93] opened 2017-08-08 07:45 UTC
Hi Team,

I am using this plugin to trigger my Multibranch Pipeline and trying to pass some variables using option 'Build Parameters'.
But when I put some Build Parameters, it is not triggering my Multibranch Pipeline and when I remove the Build Parameters it triggers.
I am already using Build Parameters option for jenkins Freestyle Project and it works fine.

Any idea, Why this combination 

> Parameterized Builds for Jenkins - Build Parameters - Multibranch Pipeline

> 

 is not working.

Thanks

**Comment by a-hacker** [comment] 2017-08-15 03:31
Hi @kishs1991, sorry for the late response. I've been on vacation this last week.

@psotona brought up a similar issue recently as well. Nothing in the code jumps out to be as problematic here but based on your scenario and those brought up in Issue #63, I suspect that the jenkins rest api is a bit different for plugins that generate jobs from Jenkinsfiles. It's possible that the url is somehow different or it's just completely unsupported.

Unfortunately, I'm going to be a little stretched for time in the upcoming months so I'm not sure when I'll get to this issue. If you have some time, could you try to manually trigger a multibranch pipeline with parameters using the rest api? Jenkins has pretty good documentation [here](https://wiki.jenkins.io/display/jenkins/remote+access+api) about how to do that. If you are successful, could you send me the URL you used? If you need any help, let me know. :)

**Comment by kishs1991** [comment] 2017-08-16 13:22
Hi @a-hacker ,

I tried manually invoking - multibranch pipelin is gettng triggerd but the parameters (e.g mybranch) passed are not accessible in Jenkinsfile.

**Jenkinsfile code snip:**

>  		properties([
> 			parameters([
> 				string(name: 'mybranch', defaultValue: 'undefined')
> 			])
> 		])
> 		println "Hello from the shebang line"
> 		println "####Printing parameter:"
> 		echo "mybranch = ${mybranch}"
> 

**curl command:**

> curl -X POST https://<"path to multibranch pipeline">/build --user ${user}:${pass} --data-urlencode json='{"parameter": [{"name":"mybranch", "value":"dev"}]}'


**Output snip:**

> 
> [Pipeline] properties
> [Pipeline] echo
> Hello from the shebang line
> [Pipeline] echo
> ####Printing parameter:
> [Pipeline] echo
> mybranch = undefined 


Correct me If I am wrong, we are passing paramteres to Jenkins job of type Multibranch - Are we expecting the right thing that is parameters should be available in Pipeline project (which is defined by Jenkinsfile).

Could you check the steps I followed and give some more input.

Thanks

**Comment by psotona** [comment] 2017-08-16 14:45
Hi, 
for me this example is working:
curl -X POST http://JENKINS/job/{JOB}/job/{BRANCH}/build --user :{TOKEN} --data-urlencode json='{"parameter": [{"name":"VAR_FOO", "value":"123"}]}'

Pipeline:
properties([
        parameters([
                string(name: 'VAR_FOO', defaultValue: 'undefined')
        ])
])
echo "{$VAR_FOO}

Pipeline output:
[Pipeline] echo
{123}


What did you use for <"path to multibranch pipeline">?
 Did you call it in format: job/{JOB}/job/{BRANCH}? 
I think it is specific for multibranch pipeline build. It also contains {branch} in path.

**Comment by a-hacker** [comment] 2017-08-17 14:11
Thanks both of you for checking this for me. The plugin is currently built for freestyle type jobs so a parameterized job sends a request to `http://JENKINS/job/{JOB}/buildWithParameters?PARAMETER=Value`.

To fully support multibranch pipelines, the `job/{BRANCH}` post-fix will need to be appended the job url before the build section. After a quick pass over the code, I believe this won't be too difficult for the regular triggers. It may require a bit more finessing for manual triggers.

In addition, the  `/buildWithParameters` syntax may not be compatible with multibranch pipelines which would explain the original behaviour described by @kishs1991. Could either of you try passing params in that way instead of through the request body? [This](https://wiki.jenkins.io/display/JENKINS/Parameterized+Build) explains some of the caveats to be aware of. If buildWithParameters can't be used then that will require an additional, more substantial change.

Thank you both again. It's a big help as I don't have experience setting up a mutibranch job myself.

**Comment by psotona** [comment] 2017-08-21 13:39
Hi, 
below is my summary of remote calls:

**1.  freestyle build request**
curl -X POST http://{JENKINS}/job/{JOB}/build 
=> not triggering the build only invoking remote repository scan (looking for new branch or commit in remote repository)

**2. freestyle parametrized build request**
curl -X POST http://{JENKINS}/job/{JOB}/buildWithParameters?PARAMETER=Value
=> returning 404 HTTP in response, <b>message</b> <u></u></p><p><b>description</b> <u>The requested resource is not available.

**3. multibranch build request**
curl -X POST http://{JENKINS}/job/{JOB}/job/{BRANCH}/build
=> invoking job build on {BRANCH}, if parameters are set in request body they are also accessible in pipeline

**4. multibranch parametrized build request**
curl -X POST http://{JENKINS}/job/{JOB}/job/{BRANCH}/buildWithParameters?PARAMETER=Value
=> error in response,  Oops!</span></h1><div id="error-description"><p>A problem occurred while processing the request
Caused by: java.lang.IllegalStateException: This build is not parameterized!
        at jenkins.model.ParameterizedJobMixIn.doBuildWithParameters(ParameterizedJobMixIn.java:224)
        at org.jenkinsci.plugins.workflow.job.WorkflowJob.doBuildWithParameters(WorkflowJob.java:305)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**Comment by a-hacker** [comment] 2017-09-02 16:50
Hey guys. I started writing up a branch to support multibranch pipelines. In my testing, I've experienced different results when triggering the jenkins rest api for a parameterized pipeline project.

Using the Jenkinsfile provided by @kishs1991, a call to http://{JENKINS}/job/{JOB}/job/{BRANCH}/**build** returns a 400 error `Nothing is submitted`. However, a call to curl -X POST http://{JENKINS}/job/{JOB}/job/{BRANCH}/**buildWithParameters**?PARAMETER=Value will trigger the pipeline. I'm wondering if a later version of some jenkins plugin or core jenkins version changes how parameterized pipelines are handled.

I am using the following versions:

- Jenkins: LTS 2.60.2
  - Pipeline: 2.5
  - Pipeline Multibranch: 2.16
  - Pipeline API: 2.20
  - Parameterized Trigger Plugin: 2.35.1
- Bitbucket Server: 5.1.0

My best guess is that the behavior changed sometime between Pipeline Multibranch: 2.10 and 2.16. If both of you could give me a list of the plugin versions you are using or upgrade and see if your curl results match mine, that would be amazing.

I also noticed that there are two different jenkins endpoints I will need to able to hit. One is the scan endpoint for the multibranch pipeline and the other is the build endpoint for the branch-specific pipelines. It seems like the trigger should dictate which endpoint is triggered but I'd like both of your advice on this. Currently, I think this makes the most sense:

- REF CREATED: scan
- PUSH EVENT: build
- REF DELETED: scan
- PR OPENED: scan?
- PR MERGED: scan?
- PR DECLINED: scan?
- PR DELETED: scan?
- AUTO MERGED: build?
- MANUAL: build

Since I don't use the multibranch pipeline setup, I don't know what really know what makes sense on the PR triggers. It seems like it might be specific to the pipeline (which is not helpful at all).

**Comment by psotona** [comment] 2017-09-11 09:35
Hi,
sorry. I was few days off. Our versions are:

Jenkins 2.27
- pipeline 2.5
- pipeline multibranch 2.16
- pipeline api 2.20
- parameterized trigger plugin 2.35.1

 Bitbucket Server: 4.9.1

Request http://{JENKINS}/job/{JOB}/job/{BRANCH}/buildWithParameters?PARAMETER=Value 
is trigerring my job now with parameter acessable in pipeline. I updated plugins a week before so maybe something were changed in our Jenkins.  But the main point is that this call is working for me now. So it could be right way to go. 

I think that PR changes should invoke build. Other changes (except MANUAL buil) should invoke scan. In these actions  change would be detectable through scan.

**Comment by a-hacker** [comment] 2017-09-11 17:04
Hi @psotona. Thanks for the update. Since it appears that the rest api call did change at some point, I'll set up the trigger to hit the buildWithParameters endpoint. This will probably make things easier anyways. I'll try to figure out when and where the change actually happened though and document it for future users.

Having the PR changes trigger a build makes sense. Do you really think push should trigger a scan though? I don't think you can pass params to the scan endpoint so a scan on a push will trigger a build but won't be parameterized. 

Also, for anyone currently wanting to use multibranch pipelines and this plugin, I recommend setting up two bitbucket triggers. The first should point to `{jobName}` with `Ref Created` and  `Ref Deleted` triggers and no params. This will trigger a scan. The second job should call `{jobName}/job/$BRANCH` and trigger on whichever combination of `Push Event` and the PR triggers you want with whatever params you'd pass into the pipeline. This should be able to dynamically resolve the branch name and build the branch-specific pipeline with the given params. This currently will not work for a manual trigger. I also have not tested this but I believe it will work. (@lindt, I think this may help you out.) I'm still committed to adding better native support for multibranch pipelines but this should be a suitable workaround.

**Comment by psotona** [comment] 2017-09-18 13:30
It depends...  But you are right. In case of PR they should invoke builds. Because during scan you will find no change in repo (no new commit added).

PR OPENED: build 
PR MERGED: build
PR DECLINED: build
PR DELETED: buil

**Comment by a-hacker** [comment] 2017-10-16 02:42
Sorry for the delay. I've had a lot going on recently. I should be done with this feature now. It's in the branch ISSUE-93. I still need to write some tests and add documentation but if anyone wants to try to build it and test it out, please feel free.

I ended up deciding on having the REF CREATED, REF DELETED, and PUSH EVENT triggers cause scans of the base multibranch pipeline while all other triggers will build the individual branch jobs.

Thanks again everyone for your help and your advice. I hope you find this implementation suitable for your workflows and if not, please give me feedback on what I can update!

**Comment by psotona** [comment] 2017-10-20 10:02
Hello, 
great news! Thx a lot. I will try it and give you know.

**Comment by psotona** [comment] 2017-10-23 13:50
We are using older Bitbucket Server version (4.9) which is incompactible with this now. I asked to upgrade the server few months ago but it is difficult to have things  moving forward here :-(  

Sorry. I cannot test it.

**Comment by a-hacker** [comment] 2017-11-25 22:35
This feature is included in version 3.2.0.

**Closed by a-hacker** 2017-11-25 22:35 UTC
