### ISSUE TITLE
I have an issue setting jenkins token, there's an exception logged in atlassian-bitbucket.log

### ISSUE THREAD

**Issue by gwsu2008** [KyleLNicholls/parameterized-builds#130] opened 2018-04-23 18:02 UTC
When click 'Save' button, an exception is logged and token is not saved.
BitBucket version 5.9.1
Parameterized Build Plugin version 3.2.3

`2018-04-23 10:53:32,404 ERROR [http-nio-7990-exec-8] <USER-ID> @JZV6W7x653x419893x1 b5ae2d 1.1.1.1,127.0.0.1 "POST /plugins/servlet/jenkins/accou
nt HTTP/1.1" c.k.s.p.ciserver.CIServlet Exception in CIServlet.doPost: null
java.lang.NullPointerException: null
        at com.kylenicholls.stash.parameterizedbuilds.ciserver.CIServlet.doPost(CIServlet.java:64)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
        at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:92)
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:181)
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:85)
        at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:85)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:112)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75)
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94)
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.plugin.connect.plugin.auth.oauth2.DefaultSalAuthenticationFilter.doFilter(DefaultSalAuthenticationFilter.java:69)
        at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:109)
        at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:32)
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:38)
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39)
        at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:90)
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73)
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:89)
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.lang.Thread.run(Thread.java:745)
        ... 226 frames trimmed
`

**Comment by a-hacker** [comment] 2018-04-23 22:47
Hi @gwsu2008. I just tested saving Jenkins settings both globally and at the project level using the versions you mentioned and had everything work as expected. I was unable to get the exception you posted. 

However, I did take a look at the line mentioned. It seems that the request created from the form returns a null "submit" element. This is a reference to the button clicked to save the Jenkins settings. After manually changing the html on the page to remove the name attribute of the save button, I could force the NullPointerException. Is it possible there is something that is manipulating the html of that page?

**Comment by lazyyogi1** [comment] 2018-04-24 15:55
Hi @a-hacker,

I am facing same issue after upgrading parameterized-builds from version 2.6.8 to 3.2.3.  Getting below error after click on "Save" button

Error Message:
2018-04-24 13:10:56,494 ERROR [http-nio-8000-exec-5] Dushyant.Kumar@example.com @JSN99Gx790x249x0 1rre3xj 121.200.57.101,47.73.63.123,47.73.63.161 "POST /plugins/servlet/jenkins/account HTTP/1.1" c.k.s.p.ciserver.CIServlet Exception in CIServlet.doPost: null
 java.lang.NullPointerException: null
 at com.kylenicholls.stash.parameterizedbuilds.ciserver.CIServlet.doPost(CIServlet.java:64)
 at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
 at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
 at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
 at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
 at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:24)
 at com.atlassian.analytics.client.filter.UniversalAnalyticsFilter.doFilter(UniversalAnalyticsFilter.java:92)
 at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39)
 at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
 at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:181)
 at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:85)
 at com.atlassian.plugin.connect.plugin.auth.scope.ApiScopingFilter.doFilter(ApiScopingFilter.java:81)
 at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
 at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:85)
 at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:112)
 at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75)
 at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94)
 at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67)
 at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
 at com.atlassian.plugin.connect.plugin.auth.oauth2.DefaultSalAuthenticationFilter.doFilter(DefaultSalAuthenticationFilter.java:69)
 at com.atlassian.plugin.connect.plugin.auth.user.ThreeLeggedAuthFilter.doFilter(ThreeLeggedAuthFilter.java:109)
 at com.atlassian.jwt.internal.servlet.JwtAuthFilter.doFilter(JwtAuthFilter.java:32)
 at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:38)
 at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:39)
 at com.atlassian.stash.internal.spring.lifecycle.LifecycleJohnsonServletFilterModuleContainerFilter.doFilter(LifecycleJohnsonServletFilterModuleContainerFilter.java:42)
 at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:90)
 at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73)
 at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:86)
 at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 at java.lang.Thread.run(Thread.java:745)
 ... 226 frames trimmed


Issue 02:

Generate API Token redirecting to wrong jenkins link: (expected user slug should be without domain)


 In Bitucket, when I tried to configure API token with jenkins by

 Manage Account --> Jenkins Settings --> Jenkins User Setting --> <Project> Token --> "Get Jenkins API Token" button.

 I get redirected to different jenkin url "https://abc.example.com/jenkins/user/dushyant.kumar_example.com/configure"

 In my jenkins, user login configured with without domain, Below is the link which i required:

 "https://abc.example.com/jenkins/user/dushyant.kumar/configure" (Without _example.com)

 current User Slug appear in link: dushyant.kumar_example.com
 expected User Slug expected in link: dushyant.kumar

 Could you please help as It need to be deployed on production server.

**Comment by a-hacker** [comment] 2018-04-24 22:55
Hi @lazyyogi1, as I said before, something seems to be malforming the html of the jenkins settings page which is causing the error. The save button should have a name attribute set to "submit". Could you see if this is the case on your Bitbucket instance?

If you need this plugin in your production environment now, I'd recommend using version 3.2.1 until this is solved as that version should not have this problem.

**Comment by gwsu2008** [comment] 2018-04-24 23:12
Hi @a-hacker,

In our case we downgraded to 3.2.1 and that fixed the problem. Not sure what would cause the issue with 'Save' button

Thanks

**Comment by lazyyogi1** [comment] 2018-04-25 15:10
Hi @a-hacker,

Thanks for input... 
Addition to this, we are also facing another issue. Could you please check and provide input on below issue as well,

Issue 02:
Clicking on "Get Jenkin API Token" under Jenkins setting, it get redirecting to different jenkins link.

Issue Description:
In Bitucket, when I tried to configure API token to integrate with Jenkins users going through setting "Manage Account --> Jenkins Settings --> Jenkins User Setting --> Token --> then click on "Get Jenkins API Token" button"

Resultant: It get redirected to different jenkin Url   "https://abc.example.com/jenkins/user/dushyant.kumar_example.com/configure"

But in my jenkins setup, we are login with Userid without domain(example: dushyant.kumar  instead of dushyant.kumar@example.com), which is alos configured with LDAP.

Below is the redirect link which we are look as (Without "_example.com"):
"https://abc.example.com/jenkins/user/dushyant.kumar/configure" 

Screenshot:
current link configured with User slug as :- "dushyant.kumar_example.com"
Require link need to configure user slug as :- "dushyant.kumar"

Really appreciate if could you please help me to resolve this issue, ( Suggest how we can manipulate with link).

**Comment by a-hacker** [comment] 2018-04-25 21:44
Sorry, I missed that bit in your original response. I see you opened a separate issue for this so I will respond there.

**Comment by alexbunk** [comment] 2018-05-08 16:47
I can fully reproduce the original issue filed by gwsu2008 in version 3.2.4.
When going to the Jenkins Settings page, after pasting the Jenkins token the Save button DOES NOT work and only returns a blank page. The token isn't saved at all.

Is there any chance this could be fixed? Currently I had to revert back to version 3.2.1 and miss out on the new release features ;-(

**Comment by alexbunk** [comment] 2018-05-10 15:40
What might a potential work-around look like that would allow us to upgrade to the latest version 3.2.4 while still being able to save Jenkins tokens. I was hoping that until a proper fix is available, there is something we can do to make this work. Please, any idea?

**Comment by alexbunk** [comment] 2018-05-10 15:42
It would also be good to remove the "can't reproduce" label since this is easily reproducible every single time when clicking the Save button.

**Comment by alexbunk** [comment] 2018-05-10 20:57
@a-hacker,
I took the time and downloaded the source code to check things out. It turns out the name attribute is never set in src/main/resources/templates/jenkins-user-settings.soy so this is definitely a bug and not a malformed html page.

`			    {call aui.form.submit}
					{param id: 'submit' /}
					{param text: 'Save' /}
					{param type: 'submit' /}
					{param extraClasses: 'aui-button-primary' /}
			    {/call}
`

I then added the name attribute, rebuilt the plugin and installed on my Bitbucket sandbox system. This fully fixes the issue but I don't really want to have to rebuild new releases all the time so it would be much better if this could be fixed for all future releases.

**Comment by a-hacker** [comment] 2018-05-10 21:17
@alexbunk, I did not realize that this was an issue with the user settings as I assuming the Jenkins settings was referring to the global or project level settings. That is my mistake and I will take another look into it when I can. Unfortunately, I am at PyCon this weekend so my time to work on a fix will be limited. If you already have a fix, would you mind creating a PR? If you do, I'll make sure to test it as soon as I find time and release the update considering the scope of this bug. Thanks!

**Comment by a-hacker** [comment] 2018-05-13 13:17
The fix has been released in version 3.2.5. Thank you all!

**Closed by a-hacker** 2018-05-13 13:17 UTC
Labels: bug
